[package]
name = "claude-rust-server"
version = "2.0.2"
edition = "2024"
description = "HTTP server with chat and health endpoints"
license = "MIT"
repository = "https://github.com/maulanasdqn/claude-rust"
readme = "../README.md"

[dependencies]
claude-rust-auth = { workspace = true }
claude-rust-config = { workspace = true }
claude-rust-errors = { workspace = true }
claude-rust-types = { workspace = true }
claude-rust-tools = { workspace = true }
claude-rust-provider = { workspace = true }
claude-rust-engine = { workspace = true }
axum = { workspace = true }
futures = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
